apiVersion: v1
kind: Service
metadata:
  name: k8hw-service
spec:
  type: LoadBalancer
  
  ports:
  - port: 9191
    protocol: TCP
    targetPort: 9191
  selector:
    app: k8hw
 


---  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8hw-deployment
  
spec:
 selector:
    matchLabels:
      app: k8hw
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: k8hw
    spec:
      containers:
      - image: karthequian/helloworld
        name: k8hw
        ports:
        - containerPort: 9191
      
